language: node_js
node_js:
- node
- '7'
- '8'
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm test
- npm run build
notifications:
  email: false
before_deploy:
- npm pack
deploy:
  provider: releases
  api_key:
    secure: Nrhgqyv2SdUWzh8P3YLezIwKeViAqnMbrAf+QILcRiHtZRNpaTmDlSCEcnBTcJKHbG8M5TzZAZK2DJy9xB4mJRx8dAsyVqC3xVQxheCg888TdI/HiSc0TDoT/dbZW0gsGcWDfrXSU5Ve5YlC2zreSoL/cAhn7lMDprH0HemRpJtBl3oFK/HbuQQ6BT0eo65soqOh0yXbj/41mFRpeKHHu8tBHCUYapZQw+9mzEjc3KtNdwa8hsrxXt9o+X9boTFfLYgxzLgJoojNb3deZqtfsGiBe2VDyklCFaQZXERm2s/qg+NvLnE8JkBNTIwDujid3ot5Q+TTrJwqaDZcAm098YtBUlVEkeFl8VG4bLzaJENKCrbujtcRZERBFVZsKpXyLMgSz8JFm8iE/CIE5sPe5ZvCdqJSx/Z32mvsmCTV16n5CfbpI2Ue/VCSLYMFO6OIYO618yFyt+3havBUJi9nZ4aMeKgOcyOwYWSTSrEZro+WDOZdS6l5IpPIAuPo5P5ikczg55TxY/JuHNcgd0y62H0CBo628jf/fkStO/HLbGewgUqkSAZVmPYgOTfOZ8+59wRpWwy50rik7FyuqWdqeMBumYGrmX6coiBW2wD3N9uyO2uUdJZpoZFx88zad6AN8wUtBvlPVDkKrbmdQYdEsurEOIKPhupKUJsP3WfeZso=
  file: deondigital-api-client-*.tgz
  on:
    all_branches: true
