language: node_js
node_js:
- node
- '7'
- '8'
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm test
- npm run build
notifications:
  email: false
before_deploy:
- npm pack
deploy:
  provider: releases
  api_key: 1bbd708dbec17ff1f6c156f22e0f04af11938453
  file: deondigital-api-client-*.tgz
  on:
    all_branches: true
