language: node_js
node_js:
- node
- '7'
- '8'
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm test
- npm run build
notifications:
  email: false
before_deploy:
- npm pack
deploy:
  provider: releases
  api_key:
    secure: VkA6nWRpSvkFv7GpSW3HMQ3emfFoqF/z4blrpeXt2E6EiowBCc3J1ULf5nhZyU2zap4rMdvJqmsyEaHTXzW3MWHgXJZrx4WByd1pHnPqpfFzcSihRb7rlwzipILsi7FDGda6zfmbCf+obUZkjbGrg+8ZVfRH5ArhGtw1ZVOEJxk6tHganZHJh96RIjpgZKEz77Q5J9OAx1kpiLzyi3wLIMZQdE+EPTPqGDpX59ZtqIp/c6w6dPQPp7R0dngGqjH4X21wEA9dKjOWqfpHnVsHzZQCSDc1V4+c5PO1XlP9KnoamT+f6Zk1VRdzlN5zjYaw/+NQIu+QJkBrbNkLtuwqCEKkG+/Fgmg+E9v3YCp872UR8A4ePgczWefOaKVSCtfh0pG+B0DLgMJhAeyWCd9yM5VltvqHaQZycpa6KP/0U5YjwtdOue7G5PP4SBy5Yy1PuNTJKrb70qUyuSPoF9dWgJ1DIcIgSGzV4tVYAx8zpxYhV3J9cvuV+cagtp0BtRUcuDX5qkVa5XoNjKjq6bupRshI1GGUXrTS2L9rAf6C2TkfW6aFTdVsJmNJI/BrhM1rBZM6+q0pT5IB7mxpy3g7PmZwUX56tN3MZM/6X+Bi4jHv8L9tClUnKOga5qQwSJ5Gmk6F6OjpEiHdEySl561nw5tPpTOElOLKGYd0grmO+s8=
  file: deondigital-api-client*.tgz
  skip_cleanup: true
  on:
    tags: true
    node_js: '10'
